# Setup
title:               QUEST on BEXUS
tagline:             'BX27'
description:         'An autonomous classification system for high-altitude balloons.'
url:                 https://jvpichowski.github.io/quest-bexus
baseurl:             ''
paginate:            5
permalink:           pretty

github:
  repo:              https://github.com/jvpichowski         

# About/contact
author:
  name:              Jan von Pichowski
  url:               https://github.com/jvpichowski
#  email:             mail@mail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
